[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/"]
ffi = true # Allow foundry to run commands directory on my machine

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
